name: struct-preserv-cyclegan
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.13.0
  - torchvision=0.14.0 
  - cudatoolkit=11.6    
  - pip:
    - apex==0.1
    - configargparse==1.7
    - contourpy==1.0.7
    - cycler==0.11.0
    - dominate==2.8.0
    - executing==2.0.1
    - fastjsonschema==2.18.1
    - fonttools==4.39.0
    - gputil==1.4.0
    - imageio==2.32.0
    - jedi==0.19.1
    - joblib==1.3.2
    - jsonpatch==1.33
    - jsonpointer==2.4
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - networkx==3.2.1
    - numpy===1.23.5
    - orjson==3.8.7
    - pandas==2.1.2
    - parso==0.8.3
    - plotly==5.18.0
    - psutil==5.9.4
    - pure-eval==0.2.2
    - pydantic==1.10.6
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - python-dotenv==1.0.0
    - python-editor==1.0.4
    - retrying==1.3.4
    - rich==13.3.2
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - stack-data==0.6.3
    - tenacity==8.2.3
    - tensorboard==2.11.0
    - threadpoolctl==3.2.0
    - visdom==0.2.4