name: sp-cyclegan
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - numpy
  - pillow
  - scipy
  - ffmpeg
  - pip
  # Local machine CPU
  - pytorch=2.6.0=cpu* 
  - torchaudio=2.6.0=cpu*
  - torchvision=0.15.2=cpu*
  # # Cluster (GPU)
  # - pytorch=2.6.0=py3.10_cuda11.8_cudnn8_0
  # - torchaudio=2.6.0=py310_cu118
  # - torchvision=0.15.2=py310_cu118
  - pip:
    - apex
    - visdom
    - dominate
    - fsspec
    - sympy
    - networkx
    - tornado